### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by ghost** [xionbig/LuckyBlock#3]
Yeah.Bruh,did this plugin also support PHP7.If have  reply please.

**Comment by NikoZazza** [comment]
not yet

**Comment by ghost** [comment]
Oh..Ok. I'll wait until its updated because all of your plugins are AAAAAAWESOMEEEEEE!!!!!

**Comment by NikoZazza** [comment]
Plugin updated for php7 https://github.com/xionbig/LuckyBlock/commit/662e797cd77b4ec63dd6235908ece4478d4daa49

**Comment by ghost** [comment]
How do I download it? Tell me..Please???

**Comment by BenasPaulikas** [comment]
https://github.com/xionbig/LuckyBlock/blob/master/LuckyBlock_v3.0.0_PHP7.phar

**Comment by ghost** [comment]
Thank You very much... Im happy now.. :)
P.S.
Sorry for all problem I have made....

**Comment by ghost** [comment]
Hey... I have a challenge for you... If you don't have anything to do...
On 30 Apr 2016 10:52, "amy qimie" amyqimie@gmail.com wrote:

Thank You very much... Im happy now.. :)
P.S.
Sorry for all problem I have made....

**Comment by BenasPaulikas** [comment]
Shoot

**Comment by ghost** [comment]
So... You want or no?

**Comment by ghost** [comment]
Im Malaysian. My english is kinda bad.
