### ISSUE TITLE
Easier Config Configuration

### ISSUE THREAD

**Issue by ghost** [xionbig/LuckyBlock#6]
Hey,Can I suggest for you to make a new config? And If ur busy I can make you one. Im willing to help.

**Comment by NikoZazza** [comment]
Tell me what is your problem, I'll see if I have to add or remove parameters in the configuration https://github.com/NikoZazza/LuckyBlock/blob/master/resources/config.yml

**Comment by ghost** [comment]
There is no problem with the config but.. Its a bit messy and hard to configurable. Can you create a new config? Or Ill edit the config.(I already have the ideas and schematic of the config)

**Comment by NikoZazza** [comment]
the current configuration makes the totally customizable plugins, if you want to give me advice I accept it. Fork the project and edit the configuration file!

**Comment by ghost** [comment]
Ok. Ill fork it but it takes time bc I'm busy with school. I'm having 2nd most important exam. So,yeah. Thanks. Also,u can close this issue.

**Comment by NikoZazza** [comment]
do not worry, even I am so busy that I can not turn on my computer :'(

**Comment by ghost** [comment]
Wow. U must be so busy. Welp cant ask anything bc everyone has their own problem. Bye. Thank You
